name: DAST - Dynamic Analysis

on:
  workflow_dispatch: # Manual workflow call
  # push:
  #     branches: [ master ]
  # pull_request:
  #     branches: [ master ]
  # schedule:
  #     - cron: '0 0 * * 6' # Runs at 00:00, every Saturday.

env:
  SECURITY-GATE-ENABLE: true
  APP_URL: "https://${{vars.OPENQUIZ_URL}}"
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions:
  security-events: write
  issues: write
  contents: read
  # id-token: write
  # actions: read
  # attestations: read
  # checks: read
  # deployments: read
  # discussions: read
  # packages: read
  # pages: read
  # pull-requests: read
  # statuses: read

jobs:
  dast-analyze:
    name: DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "[RESULT] ZAP Full Scan"
        # You may pin to the exact commit or the version.
        # uses: zaproxy/action-full-scan@75ee1686750ab1511a73b26b77a2aedd295053ed
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          # GitHub Token to create issues in the repository
          token: ${{ secrets.GITHUB_TOKEN }}
          # Target URL
          target: ${{ env.APP_URL }}
          # Relative path of the ZAP configuration file
          # rules_file_name: '.zap/rules.tsv'
          # The Docker file to be executed
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          # Additional command line options
          cmd_options: -z "-config view.locale=pt_BR"
          # The title for the GitHub issue to be created
          issue_title: 'DAST Scan Report'
          # The action status will be set to fail if ZAP identifies any alerts during the full scan
          fail_action: ${{ env.SECURITY-GATE-ENABLE }}
          # Whether Github issues should be created or not
          allow_issue_writing: true
          # The name of the artifact that contains the ZAP reports
          artifact_name: dast_scan
